version: "3.8"

services:
  backend:
    build: ./Backend
    ports:
      - "1234:1234"
    environment:
      - NODE_ENV=production
      - PORT=1234
      - MONGO_URI=${MONGO_URI}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: unless-stopped
    networks:
      - coinsafe-network

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - coinsafe-network

networks:
  coinsafe-network:
    driver: bridge
